dist: trusty
sudo: false

env:
  matrix:
  - TF_INPUT=false
  global:
  - secure: cWtYgcsnvFyQGBd6rgL+SR5szrmEj37mWVmm7QW1MOoI5yjzAY9b3WMwgdRA1jUzPayTOLM7wm8cLXLu1li3PT3yrqNsEYFJiRvUBteDU+WdFhlPUVfnkKzdEV1oW1o6Umy/JLoU4MFd4y/jcu81A9r01TRobs2Mmw8deRyKVCOSCN/Jr36v9+euX0yCL/BNK2oizhDtAI5AbpunWWrgK6JtHvjY7PrdWmSpibvsaAY+USd+629OOryQyYzTdQlId/S0W6qBNf66gJaEKBI+QyBroTkb/sVpDNXD3yNv5op0njFud9FQvv7Eg3NZOZnlmadRDtIkhZ846bQrQF4Q6MwP2nIqcE/QtSeH7Qzls/edcfBBH1NlPQw65zew9/thTCJpckgT47e6MfO9Jlf5nBIq98OAfG+sMdWprIyRiJbfapb6uR+v14+mcIpmDJ2L7ud+rbSR1tNbdJUoJeStGAaShy5ty9FZfqbc223Q0jpsb+83hr2c9iIlwP+cllfPe+HzQFRUIvwlcU+uW6OihCYvmacuOTRiPw36nGJWftZhpJM/stuxSC+MV9QTe5qF+diwRfNEoBZENBKXk1UfFvKtu91xRej+YoxBEWo4HlQJ+lWwa3Ri9KCL6Uh8b3Sq96dsZvQQ1W+D2/HYxp7bsXcqH5gV0R87ECMYQK8lqvQ=
  - secure: Xf/wycvXqGNsNlYvDu8wCqytF16/4QmW4w07mHlG4z47rGJoTbrZF0srhenq/8s+4Ho8fRsebA4C2n64A2jRV66sr/hWBSUf5aP/au9ma4Fmj4cmFv/LQFYqQ+QLlEozRz1DjALPHFvFSWdt0GyC1FvkwcJJekk6GeaP09/dvVVS4voiDN3jHE4dsLnICGAfdrSmxRHbS+oPNRLJl4BNzcThsDAVwP5yI944h/UqfcZpetrHM9ud+bIituWOdHrmx6IL6XhkX8KkcttM24/jO1l2g5AeLxhUoHzXWhrWHKlv25HCV7cxFlJUTv1zyoi/f7j4EW6sQhxvhVBJfzWI6sXxxERoc0LCgtPyfXFudYEyMhNQxN2ncdVWhXcfl0H3cR9qvLsSh5bmfJGK62q8j+eHj7bOVuvPlHTtjU4NuAUO+owUz26yQEkM/k/IKieBSvR+fVqdwAP7Wt3/mOIf45RUrzJFAPNDCFQC6+oZLDHLgLeoTT+OQgX8oL85utKqzTnzoKADet0etwqhMxtG5D+D01d999DQoDFeShUxlMs+F2aYApPWJhGmUOBxf3k1ZdG2gdZvjee6alf9bQ2ISBaYIecjTzIsXAvqbWVNoG9+GOpm7J+pSkxl+C2DKJ23+eovEqdtG5speX/vnH86/qmguP8RlPexG0bc7y3dpZ4=
before_install:
- curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.8.8/terraform_0.8.8_linux_amd64.zip
- unzip /tmp/terraform.zip -d /tmp
- mkdir ~/bin
- mv /tmp/terraform ~/bin
- export PATH="~/bin:$PATH"
script: terraform plan ./terraform
deploy:
- provider: script
  skip_cleanup: true
  script: terraform apply ./terraform
  on:
    branch: master
dd:
  secure: UT/sSC6SD/cgyZW/+1zOnrkXB2NHHgjL0ojX/ZX5fD84HohXGyBTPPw0A/SjA/mpcJL2dfCoC6bSiUHMj3cEXz3BTLUVdv3rL7RKQiPejB3KOji5klSdxcf9iB/dNdfrASgOS0q7meP9vVR2Bw7MiFBRugINoLM7NbmUeavVlm9HsLg6p9tZhP/fvJwiEaaT5BpmDUcANGpYPLlohSQeTcX+Gmcy9n1EW3Rphay3H8iFIkgomCeY23jaf6+NhPcrjKY0bGapndfEOoFHX35dz0xpnrLa1GDqstqqF1yyFXFC8Vwscr3Xt0Z//yIHAPO4kEno2inAUnElIpwr9Rpq5SFd0qPZdLbflRHEJjtnsQxIdtODApvLZ3OywSTMQc/6EboczOgQTszAt1awtB62AZkUztRMYmGZ9WusxH9HmErKZBmZ7Q7RGWfdv2RMb80BAu65loknZE55YbaTP+wcbP7xxbm21A3DVnx/XVins6mN2y+bE7YQKYm35p2cbpZ7ZrxPW/g94F19XcVVD+g1V1OCG0B0vN/L4Wlby7X65uw3jRr0VstK5QOd+3sxoGOeTFhVmPwVr7If2hOxi5PcKlj0/Z8o1uwm3eI0f/8oZWWpDMkr5FVVd0dPglmAiHumzzTlWfZ64TvZzvYu3KOb4aWAnNqQ7+Q3Sx0KMnW9tjk=
